### AspNetCore2

GET http://localhost:5000/weatherforecast

### AspNetCore3

POST http://localhost:5001/weatherforecast
Content-Type: application/json

{
"Arg1":3,
"Arg2":"exception"
}

###

GET http://localhost:5001/weatherforecast

###
